[package]
name = "docker-netmimic-plugin" # the name of the package
version = "0.1.0"    # the current version, obeying semver
authors = ["Laurent Asfaux <icidel@gmail.com>"]
edition = '2018'

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"
